namespace AccountingMetro.Context.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class LongId : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.People", "DocumentId", "dbo.Documents");
            DropForeignKey("dbo.Shifts", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.StaffDeparts", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.Employees", "PersonId", "dbo.People");
            DropForeignKey("dbo.People", "GenderId", "dbo.Genders");
            DropForeignKey("dbo.People", "StatusMariId", "dbo.StatusMaris");
            DropForeignKey("dbo.Employees", "PostId", "dbo.Posts");
            DropForeignKey("dbo.Employees", "StationId", "dbo.Stations");
            DropForeignKey("dbo.Stations", "StatusStationId", "dbo.StatusStations");
            DropForeignKey("dbo.Stations", "VetkaId", "dbo.Vetkas");
            DropForeignKey("dbo.Trains", "VetkaId", "dbo.Vetkas");
            DropForeignKey("dbo.Employees", "TrainId", "dbo.Trains");
            DropForeignKey("dbo.Trains", "StatusTrainId", "dbo.StatusTrains");
            DropForeignKey("dbo.Shifts", "StatusChangeId", "dbo.StatusShifts");
            DropIndex("dbo.Employees", new[] { "PersonId" });
            DropIndex("dbo.Employees", new[] { "PostId" });
            DropIndex("dbo.Employees", new[] { "StationId" });
            DropIndex("dbo.Employees", new[] { "TrainId" });
            DropIndex("dbo.People", new[] { "GenderId" });
            DropIndex("dbo.People", new[] { "StatusMariId" });
            DropIndex("dbo.People", new[] { "DocumentId" });
            DropIndex("dbo.Stations", new[] { "VetkaId" });
            DropIndex("dbo.Stations", new[] { "StatusStationId" });
            DropIndex("dbo.Trains", new[] { "VetkaId" });
            DropIndex("dbo.Trains", new[] { "StatusTrainId" });
            DropIndex("dbo.Shifts", new[] { "EmployeeId" });
            DropIndex("dbo.Shifts", new[] { "StatusChangeId" });
            DropIndex("dbo.StaffDeparts", new[] { "EmployeeId" });
            DropPrimaryKey("dbo.Documents");
            DropPrimaryKey("dbo.Employees");
            DropPrimaryKey("dbo.People");
            DropPrimaryKey("dbo.Genders");
            DropPrimaryKey("dbo.StatusMaris");
            DropPrimaryKey("dbo.Posts");
            DropPrimaryKey("dbo.Stations");
            DropPrimaryKey("dbo.StatusStations");
            DropPrimaryKey("dbo.Vetkas");
            DropPrimaryKey("dbo.Trains");
            DropPrimaryKey("dbo.StatusTrains");
            DropPrimaryKey("dbo.Shifts");
            DropPrimaryKey("dbo.StatusShifts");
            DropPrimaryKey("dbo.StaffDeparts");
            CreateTable(
                "dbo.StatusEmployees",
                c => new
                    {
                        Id = c.Long(nullable: false, identity: true),
                        Title = c.String(nullable: false, maxLength: 255),
                    })
                .PrimaryKey(t => t.Id);
            
            AddColumn("dbo.Employees", "StatusEmployeeId", c => c.Long(nullable: false));
            AddColumn("dbo.Shifts", "PlaceWork", c => c.String(nullable: false));
            AlterColumn("dbo.Documents", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Documents", "PassportSeries", c => c.String(nullable: false));
            AlterColumn("dbo.Documents", "Issued", c => c.String(nullable: false));
            AlterColumn("dbo.Documents", "RegistratAddress", c => c.String(nullable: false));
            AlterColumn("dbo.Employees", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Employees", "PersonId", c => c.Long(nullable: false));
            AlterColumn("dbo.Employees", "PhoneWork", c => c.String(nullable: false));
            AlterColumn("dbo.Employees", "PostId", c => c.Long(nullable: false));
            AlterColumn("dbo.Employees", "StationId", c => c.Long(nullable: false));
            AlterColumn("dbo.Employees", "TrainId", c => c.Long());
            AlterColumn("dbo.People", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.People", "LastName", c => c.String(nullable: false));
            AlterColumn("dbo.People", "FirstName", c => c.String(nullable: false));
            AlterColumn("dbo.People", "GenderId", c => c.Long(nullable: false));
            AlterColumn("dbo.People", "StatusMariId", c => c.Long(nullable: false));
            AlterColumn("dbo.People", "DocumentId", c => c.Long(nullable: false));
            AlterColumn("dbo.Genders", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Genders", "Title", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.StatusMaris", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.StatusMaris", "Title", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Posts", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Posts", "Title", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Stations", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Stations", "Title", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Stations", "VetkaId", c => c.Long(nullable: false));
            AlterColumn("dbo.Stations", "StatusStationId", c => c.Long(nullable: false));
            AlterColumn("dbo.StatusStations", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.StatusStations", "Title", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Vetkas", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Vetkas", "Title", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Trains", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Trains", "Nomer", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Trains", "VetkaId", c => c.Long(nullable: false));
            AlterColumn("dbo.Trains", "StatusTrainId", c => c.Long(nullable: false));
            AlterColumn("dbo.StatusTrains", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.StatusTrains", "Title", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.Shifts", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.Shifts", "EmployeeId", c => c.Long(nullable: false));
            AlterColumn("dbo.Shifts", "StatusChangeId", c => c.Long(nullable: false));
            AlterColumn("dbo.StatusShifts", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.StatusShifts", "Title", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.StaffDeparts", "Id", c => c.Long(nullable: false, identity: true));
            AlterColumn("dbo.StaffDeparts", "EmployeeId", c => c.Long(nullable: false));
            AlterColumn("dbo.StaffDeparts", "Login", c => c.String(nullable: false, maxLength: 255));
            AlterColumn("dbo.StaffDeparts", "Password", c => c.String(nullable: false, maxLength: 255));
            AddPrimaryKey("dbo.Documents", "Id");
            AddPrimaryKey("dbo.Employees", "Id");
            AddPrimaryKey("dbo.People", "Id");
            AddPrimaryKey("dbo.Genders", "Id");
            AddPrimaryKey("dbo.StatusMaris", "Id");
            AddPrimaryKey("dbo.Posts", "Id");
            AddPrimaryKey("dbo.Stations", "Id");
            AddPrimaryKey("dbo.StatusStations", "Id");
            AddPrimaryKey("dbo.Vetkas", "Id");
            AddPrimaryKey("dbo.Trains", "Id");
            AddPrimaryKey("dbo.StatusTrains", "Id");
            AddPrimaryKey("dbo.Shifts", "Id");
            AddPrimaryKey("dbo.StatusShifts", "Id");
            AddPrimaryKey("dbo.StaffDeparts", "Id");
            CreateIndex("dbo.Employees", "PersonId");
            CreateIndex("dbo.Employees", "PostId");
            CreateIndex("dbo.Employees", "StatusEmployeeId");
            CreateIndex("dbo.Employees", "StationId");
            CreateIndex("dbo.Employees", "TrainId");
            CreateIndex("dbo.People", "GenderId");
            CreateIndex("dbo.People", "StatusMariId");
            CreateIndex("dbo.People", "DocumentId");
            CreateIndex("dbo.Stations", "VetkaId");
            CreateIndex("dbo.Stations", "StatusStationId");
            CreateIndex("dbo.Trains", "VetkaId");
            CreateIndex("dbo.Trains", "StatusTrainId");
            CreateIndex("dbo.Shifts", "EmployeeId");
            CreateIndex("dbo.Shifts", "StatusChangeId");
            CreateIndex("dbo.StaffDeparts", "EmployeeId");
            CreateIndex("dbo.StaffDeparts", "Login", unique: true);
            AddForeignKey("dbo.Employees", "StatusEmployeeId", "dbo.StatusEmployees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.People", "DocumentId", "dbo.Documents", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Shifts", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.StaffDeparts", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Employees", "PersonId", "dbo.People", "Id", cascadeDelete: true);
            AddForeignKey("dbo.People", "GenderId", "dbo.Genders", "Id", cascadeDelete: true);
            AddForeignKey("dbo.People", "StatusMariId", "dbo.StatusMaris", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Employees", "PostId", "dbo.Posts", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Employees", "StationId", "dbo.Stations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Stations", "StatusStationId", "dbo.StatusStations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Stations", "VetkaId", "dbo.Vetkas", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Trains", "VetkaId", "dbo.Vetkas", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Employees", "TrainId", "dbo.Trains", "Id");
            AddForeignKey("dbo.Trains", "StatusTrainId", "dbo.StatusTrains", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Shifts", "StatusChangeId", "dbo.StatusShifts", "Id", cascadeDelete: true);
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Shifts", "StatusChangeId", "dbo.StatusShifts");
            DropForeignKey("dbo.Trains", "StatusTrainId", "dbo.StatusTrains");
            DropForeignKey("dbo.Employees", "TrainId", "dbo.Trains");
            DropForeignKey("dbo.Trains", "VetkaId", "dbo.Vetkas");
            DropForeignKey("dbo.Stations", "VetkaId", "dbo.Vetkas");
            DropForeignKey("dbo.Stations", "StatusStationId", "dbo.StatusStations");
            DropForeignKey("dbo.Employees", "StationId", "dbo.Stations");
            DropForeignKey("dbo.Employees", "PostId", "dbo.Posts");
            DropForeignKey("dbo.People", "StatusMariId", "dbo.StatusMaris");
            DropForeignKey("dbo.People", "GenderId", "dbo.Genders");
            DropForeignKey("dbo.Employees", "PersonId", "dbo.People");
            DropForeignKey("dbo.StaffDeparts", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.Shifts", "EmployeeId", "dbo.Employees");
            DropForeignKey("dbo.People", "DocumentId", "dbo.Documents");
            DropForeignKey("dbo.Employees", "StatusEmployeeId", "dbo.StatusEmployees");
            DropIndex("dbo.StaffDeparts", new[] { "Login" });
            DropIndex("dbo.StaffDeparts", new[] { "EmployeeId" });
            DropIndex("dbo.Shifts", new[] { "StatusChangeId" });
            DropIndex("dbo.Shifts", new[] { "EmployeeId" });
            DropIndex("dbo.Trains", new[] { "StatusTrainId" });
            DropIndex("dbo.Trains", new[] { "VetkaId" });
            DropIndex("dbo.Stations", new[] { "StatusStationId" });
            DropIndex("dbo.Stations", new[] { "VetkaId" });
            DropIndex("dbo.People", new[] { "DocumentId" });
            DropIndex("dbo.People", new[] { "StatusMariId" });
            DropIndex("dbo.People", new[] { "GenderId" });
            DropIndex("dbo.Employees", new[] { "TrainId" });
            DropIndex("dbo.Employees", new[] { "StationId" });
            DropIndex("dbo.Employees", new[] { "StatusEmployeeId" });
            DropIndex("dbo.Employees", new[] { "PostId" });
            DropIndex("dbo.Employees", new[] { "PersonId" });
            DropPrimaryKey("dbo.StaffDeparts");
            DropPrimaryKey("dbo.StatusShifts");
            DropPrimaryKey("dbo.Shifts");
            DropPrimaryKey("dbo.StatusTrains");
            DropPrimaryKey("dbo.Trains");
            DropPrimaryKey("dbo.Vetkas");
            DropPrimaryKey("dbo.StatusStations");
            DropPrimaryKey("dbo.Stations");
            DropPrimaryKey("dbo.Posts");
            DropPrimaryKey("dbo.StatusMaris");
            DropPrimaryKey("dbo.Genders");
            DropPrimaryKey("dbo.People");
            DropPrimaryKey("dbo.Employees");
            DropPrimaryKey("dbo.Documents");
            AlterColumn("dbo.StaffDeparts", "Password", c => c.String(nullable: false));
            AlterColumn("dbo.StaffDeparts", "Login", c => c.String(nullable: false));
            AlterColumn("dbo.StaffDeparts", "EmployeeId", c => c.Int(nullable: false));
            AlterColumn("dbo.StaffDeparts", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.StatusShifts", "Title", c => c.String());
            AlterColumn("dbo.StatusShifts", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Shifts", "StatusChangeId", c => c.Int(nullable: false));
            AlterColumn("dbo.Shifts", "EmployeeId", c => c.Int(nullable: false));
            AlterColumn("dbo.Shifts", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.StatusTrains", "Title", c => c.String());
            AlterColumn("dbo.StatusTrains", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Trains", "StatusTrainId", c => c.Int(nullable: false));
            AlterColumn("dbo.Trains", "VetkaId", c => c.Int(nullable: false));
            AlterColumn("dbo.Trains", "Nomer", c => c.String());
            AlterColumn("dbo.Trains", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Vetkas", "Title", c => c.String());
            AlterColumn("dbo.Vetkas", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.StatusStations", "Title", c => c.String());
            AlterColumn("dbo.StatusStations", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Stations", "StatusStationId", c => c.Int(nullable: false));
            AlterColumn("dbo.Stations", "VetkaId", c => c.Int(nullable: false));
            AlterColumn("dbo.Stations", "Title", c => c.String());
            AlterColumn("dbo.Stations", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Posts", "Title", c => c.String());
            AlterColumn("dbo.Posts", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.StatusMaris", "Title", c => c.String());
            AlterColumn("dbo.StatusMaris", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Genders", "Title", c => c.String());
            AlterColumn("dbo.Genders", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.People", "DocumentId", c => c.Int(nullable: false));
            AlterColumn("dbo.People", "StatusMariId", c => c.Int(nullable: false));
            AlterColumn("dbo.People", "GenderId", c => c.Int(nullable: false));
            AlterColumn("dbo.People", "FirstName", c => c.String());
            AlterColumn("dbo.People", "LastName", c => c.String());
            AlterColumn("dbo.People", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Employees", "TrainId", c => c.Int());
            AlterColumn("dbo.Employees", "StationId", c => c.Int(nullable: false));
            AlterColumn("dbo.Employees", "PostId", c => c.Int(nullable: false));
            AlterColumn("dbo.Employees", "PhoneWork", c => c.String());
            AlterColumn("dbo.Employees", "PersonId", c => c.Int(nullable: false));
            AlterColumn("dbo.Employees", "Id", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Documents", "RegistratAddress", c => c.String());
            AlterColumn("dbo.Documents", "Issued", c => c.String());
            AlterColumn("dbo.Documents", "PassportSeries", c => c.String());
            AlterColumn("dbo.Documents", "Id", c => c.Int(nullable: false, identity: true));
            DropColumn("dbo.Shifts", "PlaceWork");
            DropColumn("dbo.Employees", "StatusEmployeeId");
            DropTable("dbo.StatusEmployees");
            AddPrimaryKey("dbo.StaffDeparts", "Id");
            AddPrimaryKey("dbo.StatusShifts", "Id");
            AddPrimaryKey("dbo.Shifts", "Id");
            AddPrimaryKey("dbo.StatusTrains", "Id");
            AddPrimaryKey("dbo.Trains", "Id");
            AddPrimaryKey("dbo.Vetkas", "Id");
            AddPrimaryKey("dbo.StatusStations", "Id");
            AddPrimaryKey("dbo.Stations", "Id");
            AddPrimaryKey("dbo.Posts", "Id");
            AddPrimaryKey("dbo.StatusMaris", "Id");
            AddPrimaryKey("dbo.Genders", "Id");
            AddPrimaryKey("dbo.People", "Id");
            AddPrimaryKey("dbo.Employees", "Id");
            AddPrimaryKey("dbo.Documents", "Id");
            CreateIndex("dbo.StaffDeparts", "EmployeeId");
            CreateIndex("dbo.Shifts", "StatusChangeId");
            CreateIndex("dbo.Shifts", "EmployeeId");
            CreateIndex("dbo.Trains", "StatusTrainId");
            CreateIndex("dbo.Trains", "VetkaId");
            CreateIndex("dbo.Stations", "StatusStationId");
            CreateIndex("dbo.Stations", "VetkaId");
            CreateIndex("dbo.People", "DocumentId");
            CreateIndex("dbo.People", "StatusMariId");
            CreateIndex("dbo.People", "GenderId");
            CreateIndex("dbo.Employees", "TrainId");
            CreateIndex("dbo.Employees", "StationId");
            CreateIndex("dbo.Employees", "PostId");
            CreateIndex("dbo.Employees", "PersonId");
            AddForeignKey("dbo.Shifts", "StatusChangeId", "dbo.StatusShifts", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Trains", "StatusTrainId", "dbo.StatusTrains", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Employees", "TrainId", "dbo.Trains", "Id");
            AddForeignKey("dbo.Trains", "VetkaId", "dbo.Vetkas", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Stations", "VetkaId", "dbo.Vetkas", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Stations", "StatusStationId", "dbo.StatusStations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Employees", "StationId", "dbo.Stations", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Employees", "PostId", "dbo.Posts", "Id", cascadeDelete: true);
            AddForeignKey("dbo.People", "StatusMariId", "dbo.StatusMaris", "Id", cascadeDelete: true);
            AddForeignKey("dbo.People", "GenderId", "dbo.Genders", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Employees", "PersonId", "dbo.People", "Id", cascadeDelete: true);
            AddForeignKey("dbo.StaffDeparts", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.Shifts", "EmployeeId", "dbo.Employees", "Id", cascadeDelete: true);
            AddForeignKey("dbo.People", "DocumentId", "dbo.Documents", "Id", cascadeDelete: true);
        }
    }
}
