// <auto-generated />
namespace AccountingMetro.Context.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class FIOStaff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FIOStaff));
        
        string IMigrationMetadata.Id
        {
            get { return "202406060901527_FIOStaff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
